server:
  port: 9090
spring:
  application:
    name: first-app
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/first-app
    username: postgres
    password: postgres
  jpa:
    database: POSTGRESQL
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
    show-sql: true

logging:
  level:
    root: warn
